// <auto-generated />
namespace SycData.Restaurante.Infra.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class asd22dsd233 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asd22dsd233));
        
        string IMigrationMetadata.Id
        {
            get { return "201906132109587_asd22dsd233"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
