// <auto-generated />
namespace SycData.Restaurante.Infra.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rest));
        
        string IMigrationMetadata.Id
        {
            get { return "201906111521313_Rest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
